import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Badge } from "@/components/ui/badge";
import { Brain, Database, MapPin, Sparkles, CheckCircle2, Loader2 } from "lucide-react";
import { cn } from "@/lib/utils";

type AgentStep = {
  id: string;
  name: string;
  description: string;
  icon: React.ReactNode;
  status: "draft" | "analyzing_intent" | "researching_destination" | "curating_activities" | "generating_itinerary" | "completed";
};

const agents: AgentStep[] = [
  {
    id: "analyzing_intent",
    name: "Agent 1: Intent Analyzer",
    description: "Analyzing your preferences, budget, and travel motivations",
    icon: <Brain className="h-5 w-5" />,
    status: "analyzing_intent",
  },
  {
    id: "researching_destination",
    name: "Agent 2: Destination Researcher",
    description: "Fetching real flight & hotel data, researching destination details",
    icon: <Database className="h-5 w-5" />,
    status: "researching_destination",
  },
  {
    id: "curating_activities",
    name: "Agent 3: Activity Curator",
    description: "Curating personalized activities based on your travel style",
    icon: <MapPin className="h-5 w-5" />,
    status: "curating_activities",
  },
  {
    id: "generating_itinerary",
    name: "Agent 4: Itinerary Generator",
    description: "Synthesizing all research into your detailed itinerary",
    icon: <Sparkles className="h-5 w-5" />,
    status: "generating_itinerary",
  },
];

interface AgentProgressTrackerProps {
  currentStatus: string;
  className?: string;
}

export const AgentProgressTracker = ({ currentStatus, className }: AgentProgressTrackerProps) => {
  const getAgentState = (agentStatus: string) => {
    const statusOrder = ["draft", "analyzing_intent", "researching_destination", "curating_activities", "generating_itinerary", "completed"];
    const currentIndex = statusOrder.indexOf(currentStatus);
    const agentIndex = statusOrder.indexOf(agentStatus);
    
    if (currentStatus === "completed") return "completed";
    if (agentIndex < currentIndex) return "completed";
    if (agentIndex === currentIndex) return "active";
    return "pending";
  };

  const getProgressValue = () => {
    switch (currentStatus) {
      case "draft": return 0;
      case "analyzing_intent": return 25;
      case "researching_destination": return 50;
      case "curating_activities": return 75;
      case "generating_itinerary": return 90;
      case "completed": return 100;
      default: return 0;
    }
  };

  const isProcessing = ["analyzing_intent", "researching_destination", "curating_activities", "generating_itinerary"].includes(currentStatus);

  return (
    <Card className={cn("border-2", isProcessing && "border-primary/50", className)}>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              {isProcessing ? (
                <>
                  <Loader2 className="h-5 w-5 animate-spin text-primary" />
                  <span>AI Agents Working</span>
                </>
              ) : currentStatus === "completed" ? (
                <>
                  <CheckCircle2 className="h-5 w-5 text-green-500" />
                  <span>Itinerary Complete</span>
                </>
              ) : (
                <span>Processing Status</span>
              )}
            </CardTitle>
            <CardDescription className="mt-1">
              {isProcessing ? "Your itinerary is being generated by our specialized AI agents" : "All agents have completed their work"}
            </CardDescription>
          </div>
          <Badge variant={currentStatus === "completed" ? "default" : "secondary"} className="text-lg px-4 py-2">
            {getProgressValue()}%
          </Badge>
        </div>
        <Progress value={getProgressValue()} className="h-2 mt-4" />
      </CardHeader>
      <CardContent>
        <div className="space-y-4">
          {agents.map((agent) => {
            const state = getAgentState(agent.status);
            
            return (
              <div
                key={agent.id}
                className={cn(
                  "flex items-start gap-4 p-4 rounded-lg transition-all",
                  state === "active" && "bg-primary/10 border-2 border-primary/50",
                  state === "completed" && "bg-muted/50",
                  state === "pending" && "opacity-50"
                )}
              >
                <div
                  className={cn(
                    "flex items-center justify-center w-10 h-10 rounded-full shrink-0 transition-colors",
                    state === "active" && "bg-primary text-primary-foreground animate-pulse",
                    state === "completed" && "bg-green-500 text-white",
                    state === "pending" && "bg-muted text-muted-foreground"
                  )}
                >
                  {state === "completed" ? (
                    <CheckCircle2 className="h-5 w-5" />
                  ) : state === "active" ? (
                    <Loader2 className="h-5 w-5 animate-spin" />
                  ) : (
                    agent.icon
                  )}
                </div>
                
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <h3 className={cn("font-semibold", state === "active" && "text-primary")}>
                      {agent.name}
                    </h3>
                    {state === "active" && (
                      <Badge variant="default" className="text-xs">
                        Working
                      </Badge>
                    )}
                    {state === "completed" && (
                      <Badge variant="outline" className="text-xs bg-green-500/10 text-green-700 dark:text-green-400 border-green-500/20">
                        Done
                      </Badge>
                    )}
                  </div>
                  <p className={cn("text-sm", state === "pending" ? "text-muted-foreground" : "text-muted-foreground")}>
                    {agent.description}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
        
        {isProcessing && (
          <div className="mt-6 p-4 bg-primary/5 rounded-lg border border-primary/20">
            <p className="text-sm text-muted-foreground flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-primary" />
              This page will update automatically as agents complete their work
            </p>
          </div>
        )}
      </CardContent>
    </Card>
  );
};
